# Generated by Django 6.0.4 on 2026-04-24 00:00

import core.utils
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=core.utils.make_logo_upload_path)),
                ('logo_dark', models.ImageField(blank=True, null=True, upload_to=core.utils.make_logo_upload_path)),
                ('favicon', models.ImageField(blank=True, null=True, upload_to=core.utils.make_logo_upload_path)),
                ('primary_color', models.CharField(default='#004274', max_length=7)),
                ('secondary_color', models.CharField(default='#0A1F44', max_length=7)),
                ('accent_color', models.CharField(default='#C9A974', max_length=7)),
                ('background_color', models.CharField(default='#FFFFFF', max_length=7)),
                ('surface_color', models.CharField(default='#F9FAFB', max_length=7)),
                ('text_primary_color', models.CharField(default='#111827', max_length=7)),
                ('text_secondary_color', models.CharField(default='#4B5563', max_length=7)),
                ('nav_background', models.CharField(default='#FFFFFF', max_length=7)),
                ('footer_background', models.CharField(default='#0A1F44', max_length=7)),
                ('footer_text_color', models.CharField(default='#FFFFFF', max_length=7)),
                ('border_color', models.CharField(default='#E5E7EB', max_length=7)),
                ('success_color', models.CharField(default='#10B981', max_length=7)),
                ('warning_color', models.CharField(default='#F59E0B', max_length=7)),
                ('error_color', models.CharField(default='#EF4444', max_length=7)),
                ('dark_bg_color', models.CharField(default='#0B1220', max_length=7)),
                ('dark_surface_color', models.CharField(default='#161F30', max_length=7)),
                ('dark_text_primary', models.CharField(default='#F9FAFB', max_length=7)),
                ('dark_border_color', models.CharField(default='#1F2937', max_length=7)),
                ('font_family_heading', models.CharField(choices=[('Inter', 'Inter'), ('Poppins', 'Poppins'), ('Roboto', 'Roboto'), ('Lato', 'Lato'), ('Open Sans', 'Open Sans'), ('Montserrat', 'Montserrat'), ('Raleway', 'Raleway'), ('Nunito', 'Nunito'), ('Playfair Display', 'Playfair Display'), ('Merriweather', 'Merriweather'), ('Source Sans Pro', 'Source Sans Pro'), ('Oswald', 'Oswald')], default='Inter', max_length=50)),
                ('font_family_body', models.CharField(choices=[('Inter', 'Inter'), ('Poppins', 'Poppins'), ('Roboto', 'Roboto'), ('Lato', 'Lato'), ('Open Sans', 'Open Sans'), ('Montserrat', 'Montserrat'), ('Raleway', 'Raleway'), ('Nunito', 'Nunito'), ('Playfair Display', 'Playfair Display'), ('Merriweather', 'Merriweather'), ('Source Sans Pro', 'Source Sans Pro'), ('Oswald', 'Oswald')], default='Inter', max_length=50)),
                ('font_size_base', models.FloatField(default=16.0)),
                ('font_weight_heading', models.CharField(default='700', max_length=10)),
                ('border_radius_base', models.FloatField(default=8.0)),
                ('nav_style', models.CharField(choices=[('fixed', 'Fixed'), ('sticky', 'Sticky'), ('static', 'Static')], default='fixed', max_length=20)),
                ('dark_mode_enabled', models.BooleanField(default=True)),
                ('custom_css', models.TextField(blank=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='theme_config', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Theme Config',
            },
        ),
    ]
