# Generated by Django 6.0.4 on 2026-04-24 00:00

import core.utils
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference_id', models.CharField(blank=True, db_index=True, max_length=50)),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(max_length=300)),
                ('description', models.TextField()),
                ('property_type', models.CharField(choices=[('villa', 'Villa'), ('bungalow', 'Bungalow'), ('duplex', 'Duplex'), ('penthouse', 'Penthouse'), ('apartment', 'Apartment'), ('mansion', 'Mansion'), ('estate', 'Estate'), ('townhouse', 'Townhouse'), ('commercial', 'Commercial'), ('land', 'Land')], default='bungalow', max_length=20)),
                ('listing_type', models.CharField(choices=[('sale', 'For Sale'), ('rent', 'For Rent'), ('both', 'Sale & Rent')], default='sale', max_length=10)),
                ('status', models.CharField(choices=[('available', 'Available'), ('sold', 'Sold'), ('rented', 'Rented'), ('pending', 'Pending'), ('off_market', 'Off Market')], default='available', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('GHS', 'GHS (Cedis)'), ('NGN', 'NGN (Naira)'), ('KES', 'KES (Shilling)'), ('ZAR', 'ZAR (Rand)'), ('EUR', 'EUR'), ('GBP', 'GBP')], default='USD', max_length=5)),
                ('price_negotiable', models.BooleanField(default=False)),
                ('rental_period', models.CharField(blank=True, max_length=20)),
                ('bedrooms', models.PositiveSmallIntegerField(default=0)),
                ('bathrooms', models.PositiveSmallIntegerField(default=0)),
                ('toilets', models.PositiveSmallIntegerField(default=0)),
                ('sqft', models.PositiveIntegerField(default=0)),
                ('area_sqm', models.FloatField(default=0)),
                ('parking_spaces', models.PositiveSmallIntegerField(default=0)),
                ('year_built', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('energy_class', models.CharField(blank=True, max_length=5)),
                ('energy_performance_index', models.FloatField(blank=True, null=True)),
                ('floors', models.PositiveSmallIntegerField(default=1)),
                ('boys_quarters', models.BooleanField(default=False)),
                ('address', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=100)),
                ('area', models.CharField(blank=True, max_length=100)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(default='Ghana', max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('features', models.JSONField(default=list)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('virtual_tour_url', models.URLField(blank=True)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('inquiry_count', models.PositiveIntegerField(default=0)),
                ('assigned_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_properties', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_properties', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('message', models.TextField()),
                ('preferred_tour_date', models.DateField(blank=True, null=True)),
                ('is_processed', models.BooleanField(default=False)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='properties.property')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=core.utils.make_property_upload_path)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('is_primary', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property')),
            ],
            options={
                'ordering': ['order', '-is_primary'],
            },
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['tenant', 'status', 'is_published'], name='properties__tenant__c21344_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['tenant', 'property_type'], name='properties__tenant__dc153c_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['tenant', 'city'], name='properties__tenant__981969_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['tenant', 'listing_type'], name='properties__tenant__6d2bcd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='property',
            unique_together={('tenant', 'slug')},
        ),
    ]
